--------------------------------------------------------
--  파일이 생성됨 - 토요일-12월-13-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_MOVIE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_MOVIE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PAY_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_PAY_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RES_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_RES_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RES_SEAT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_RES_SEAT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_REVIEW_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_REVIEW_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_RULE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_RULE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCREENING_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_SCREENING_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SCR_SEAT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_SCR_SEAT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_SEAT_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_SEAT_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_THEATER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_THEATER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_ID
--------------------------------------------------------

   CREATE SEQUENCE  "C##MOVIE_SNIPER"."SEQ_USER_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table MOVIE
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."MOVIE" 
   (	"MOVIE_ID" NUMBER(10,0), 
	"TITLE" VARCHAR2(200 BYTE), 
	"GENRE" VARCHAR2(100 BYTE), 
	"RUNTIME" NUMBER(4,0), 
	"GRADE" VARCHAR2(20 BYTE), 
	"RELEASE_DATE" DATE, 
	"POSTER" VARCHAR2(500 BYTE), 
	"DIRECTOR" VARCHAR2(100 BYTE), 
	"CAST" VARCHAR2(500 BYTE), 
	"END_DATE" DATE, 
	"SYNOPSIS" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SYNOPSIS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table PAYMENT
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."PAYMENT" 
   (	"PAYMENT_ID" NUMBER(15,0), 
	"RESERVATION_ID" NUMBER(15,0), 
	"PAYMENT_METHOD" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"AMOUNT" NUMBER(8,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"REFUNDED_AT" TIMESTAMP (6), 
	"REFUND_AMOUNT" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRICERULE
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."PRICERULE" 
   (	"RULE_ID" NUMBER(5,0), 
	"SEAT_COEF" VARCHAR2(1000 BYTE), 
	"BOOK_TIME_COEF" VARCHAR2(1000 BYTE), 
	"DISCOUNT_RATE" VARCHAR2(1000 BYTE), 
	"MIN_LIMIT" NUMBER(7,0), 
	"MAX_LIMIT" NUMBER(7,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."RESERVATION" 
   (	"RESERVATION_ID" NUMBER(15,0), 
	"USER_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"QR_CODE" VARCHAR2(500 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"CANCELLED_AT" TIMESTAMP (6), 
	"FINAL_PRICE" NUMBER(8,0), 
	"DISCOUNT_RATE" NUMBER(3,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RESERVATIONSEAT
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" 
   (	"RESERVATION_SEAT_ID" NUMBER(15,0), 
	"RESERVATION_ID" NUMBER(15,0), 
	"SCREENING_SEAT_ID" NUMBER(15,0), 
	"PRICE" NUMBER(8,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REVIEW
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."REVIEW" 
   (	"REVIEW_ID" NUMBER(15,0), 
	"USER_ID" NUMBER(10,0), 
	"SCREENING_SEAT_ID" NUMBER(15,0), 
	"SIGHT_SCORE" NUMBER(2,1), 
	"SOUND_SCORE" NUMBER(2,1), 
	"OVERALL_SCORE" NUMBER(2,1), 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCREENING
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."SCREENING" 
   (	"SCREENING_ID" NUMBER(15,0), 
	"MOVIE_ID" NUMBER(10,0), 
	"THEATER_ID" NUMBER(5,0), 
	"SCREEN_DATE" DATE, 
	"START_TIME" VARCHAR2(5 BYTE), 
	"END_TIME" VARCHAR2(5 BYTE), 
	"BASE_PRICE" NUMBER(7,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCREENINGSEAT
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" 
   (	"SCREENING_SEAT_ID" NUMBER(15,0), 
	"SCREENING_ID" NUMBER(15,0), 
	"SEAT_ID" NUMBER(10,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"LOCKED_AT" TIMESTAMP (6), 
	"LOCK_EXPIRES_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table THEATER
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."THEATER" 
   (	"THEATER_ID" NUMBER(5,0), 
	"THEATER_NAME" VARCHAR2(100 BYTE), 
	"LOCATION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table THEATERSEAT
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."THEATERSEAT" 
   (	"SEAT_ID" NUMBER(10,0), 
	"THEATER_ID" NUMBER(5,0), 
	"ROW_NUM" VARCHAR2(5 BYTE), 
	"COL_NUM" NUMBER(3,0), 
	"SEAT_CODE" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"GRADE" VARCHAR2(10 BYTE), 
	"WHEELCHAIR" CHAR(1 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##MOVIE_SNIPER"."USERS" 
   (	"USER_ID" NUMBER(10,0), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(256 BYTE), 
	"NAME" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"PAYMENT" VARCHAR2(50 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSDATE, 
	"UPDATED_AT" TIMESTAMP (6)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into C##MOVIE_SNIPER.MOVIE
SET DEFINE OFF;
Insert into C##MOVIE_SNIPER.MOVIE (MOVIE_ID,TITLE,GENRE,RUNTIME,GRADE,RELEASE_DATE,POSTER,DIRECTOR,CAST,END_DATE) values (1,'주토피아 2','애니메이션',108,'전체관람가',to_date('25/11/26','RR/MM/DD'),'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgEFQcODlfLfIU7eKfQd235ifOeaVDFxw40Lfof78KMXtuS-nj','자레시 부시','지니퍼 굿윈, 제이슨 베이트먼, 키 호이콴',to_date('25/12/26','RR/MM/DD'));
Insert into C##MOVIE_SNIPER.MOVIE (MOVIE_ID,TITLE,GENRE,RUNTIME,GRADE,RELEASE_DATE,POSTER,DIRECTOR,CAST,END_DATE) values (23,'극장판 주술회전: 시부야사변 X 사멸회유','애니메이션',87,'전체관람가',to_date('25/12/03','RR/MM/DD'),'https://search.pstatic.net/common?quality=75&direct=true&src=https%3A%2F%2Fmovie-phinf.pstatic.net%2F20251203_36%2F1764728349013yoGaB_JPEG%2Fmovie_image.jpg','고쇼조노 쇼타','없음',to_date('26/01/03','RR/MM/DD'));
REM INSERTING into C##MOVIE_SNIPER.PAYMENT
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.PRICERULE
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.RESERVATION
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.RESERVATIONSEAT
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.REVIEW
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.SCREENING
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.SCREENINGSEAT
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.THEATER
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.THEATERSEAT
SET DEFINE OFF;
REM INSERTING into C##MOVIE_SNIPER.USERS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_MOVIE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_MOVIE" ON "C##MOVIE_SNIPER"."MOVIE" ("MOVIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAYMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_PAYMENT" ON "C##MOVIE_SNIPER"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRICE_RULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_PRICE_RULE" ON "C##MOVIE_SNIPER"."PRICERULE" ("RULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_RESERVATION" ON "C##MOVIE_SNIPER"."RESERVATION" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RES_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_RES_SEAT" ON "C##MOVIE_SNIPER"."RESERVATIONSEAT" ("RESERVATION_SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_REVIEW" ON "C##MOVIE_SNIPER"."REVIEW" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCREENING
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_SCREENING" ON "C##MOVIE_SNIPER"."SCREENING" ("SCREENING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCR_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_SCR_SEAT" ON "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_THEATER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_THEATER" ON "C##MOVIE_SNIPER"."THEATER" ("THEATER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_THEATER_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_THEATER_SEAT" ON "C##MOVIE_SNIPER"."THEATERSEAT" ("SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_USERS" ON "C##MOVIE_SNIPER"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000080052C00011$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."SYS_IL0000080052C00011$$" ON "C##MOVIE_SNIPER"."MOVIE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index UQ_SCR_SEAT_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."UQ_SCR_SEAT_UNIQUE" ON "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_ID", "SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."UQ_USERS_EMAIL" ON "C##MOVIE_SNIPER"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_MOVIE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_MOVIE" ON "C##MOVIE_SNIPER"."MOVIE" ("MOVIE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PAYMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_PAYMENT" ON "C##MOVIE_SNIPER"."PAYMENT" ("PAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRICE_RULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_PRICE_RULE" ON "C##MOVIE_SNIPER"."PRICERULE" ("RULE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_RESERVATION" ON "C##MOVIE_SNIPER"."RESERVATION" ("RESERVATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_RES_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_RES_SEAT" ON "C##MOVIE_SNIPER"."RESERVATIONSEAT" ("RESERVATION_SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_REVIEW
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_REVIEW" ON "C##MOVIE_SNIPER"."REVIEW" ("REVIEW_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCREENING
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_SCREENING" ON "C##MOVIE_SNIPER"."SCREENING" ("SCREENING_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SCR_SEAT_UNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."UQ_SCR_SEAT_UNIQUE" ON "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_ID", "SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SCR_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_SCR_SEAT" ON "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_THEATER
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_THEATER" ON "C##MOVIE_SNIPER"."THEATER" ("THEATER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_THEATER_SEAT
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_THEATER_SEAT" ON "C##MOVIE_SNIPER"."THEATERSEAT" ("SEAT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."PK_USERS" ON "C##MOVIE_SNIPER"."USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_USERS_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##MOVIE_SNIPER"."UQ_USERS_EMAIL" ON "C##MOVIE_SNIPER"."USERS" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table MOVIE
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("GENRE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("RUNTIME" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" MODIFY ("RELEASE_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY ("MOVIE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("PAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("PAYMENT_METHOD" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" ADD CONSTRAINT "CHK_PAY_STATUS" CHECK (status IN ('PAID', 'REFUNDED')) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY ("PAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRICERULE
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("RULE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("SEAT_COEF" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("BOOK_TIME_COEF" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("DISCOUNT_RATE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("MIN_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("MAX_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" ADD CONSTRAINT "PK_PRICE_RULE" PRIMARY KEY ("RULE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" ADD CONSTRAINT "CHK_JSON_SEAT" CHECK (seat_coef IS JSON) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" ADD CONSTRAINT "CHK_JSON_TIME" CHECK (book_time_coef IS JSON) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."PRICERULE" ADD CONSTRAINT "CHK_JSON_DISC" CHECK (discount_rate IS JSON) ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" MODIFY ("FINAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" ADD CONSTRAINT "CHK_RES_STATUS" CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESERVATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESERVATIONSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" MODIFY ("RESERVATION_SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" MODIFY ("RESERVATION_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" MODIFY ("SCREENING_SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" ADD CONSTRAINT "PK_RES_SEAT" PRIMARY KEY ("RESERVATION_SEAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("REVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("SCREENING_SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("SIGHT_SCORE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("SOUND_SCORE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("OVERALL_SCORE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "CHK_SIGHT_SCORE" CHECK (sight_score BETWEEN 0 AND 5) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "CHK_SOUND_SCORE" CHECK (sound_score BETWEEN 0 AND 5) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "CHK_OVERALL_SCORE" CHECK (overall_score BETWEEN 0 AND 5) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY ("REVIEW_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCREENING
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("SCREENING_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("MOVIE_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("THEATER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("SCREEN_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("START_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("END_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" MODIFY ("BASE_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" ADD CONSTRAINT "PK_SCREENING" PRIMARY KEY ("SCREENING_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCREENINGSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" MODIFY ("SCREENING_SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" MODIFY ("SCREENING_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" MODIFY ("SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" ADD CONSTRAINT "CHK_SS_STATUS" CHECK (status IN ('AVAILABLE', 'LOCKED', 'BOOKED')) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" ADD CONSTRAINT "PK_SCR_SEAT" PRIMARY KEY ("SCREENING_SEAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" ADD CONSTRAINT "UQ_SCR_SEAT_UNIQUE" UNIQUE ("SCREENING_ID", "SEAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table THEATER
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."THEATER" MODIFY ("THEATER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATER" MODIFY ("THEATER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATER" ADD CONSTRAINT "PK_THEATER" PRIMARY KEY ("THEATER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table THEATERSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("SEAT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("THEATER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("ROW_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("COL_NUM" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("SEAT_CODE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("GRADE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" MODIFY ("WHEELCHAIR" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" ADD CONSTRAINT "CHK_TS_WHEELCHAIR" CHECK (wheelchair IN ('Y', 'N')) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" ADD CONSTRAINT "CHK_TS_TYPE" CHECK (type IN ('SEAT', 'SCREEN', 'AISLE', 'RAMP', 'SPEAKER', 'EXIT')) ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" ADD CONSTRAINT "PK_THEATER_SEAT" PRIMARY KEY ("SEAT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" ADD CONSTRAINT "CHK_TS_GRADE" CHECK (grade IN ('A', 'B', 'C')) ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" ADD CONSTRAINT "PK_USERS" PRIMARY KEY ("USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."USERS" ADD CONSTRAINT "UQ_USERS_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAYMENT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."PAYMENT" ADD CONSTRAINT "FK_PAY_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "C##MOVIE_SNIPER"."RESERVATION" ("RESERVATION_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATION" ADD CONSTRAINT "FK_RES_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##MOVIE_SNIPER"."USERS" ("USER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVATIONSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" ADD CONSTRAINT "FK_RS_RESERVATION" FOREIGN KEY ("RESERVATION_ID")
	  REFERENCES "C##MOVIE_SNIPER"."RESERVATION" ("RESERVATION_ID") ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."RESERVATIONSEAT" ADD CONSTRAINT "FK_RS_SCR_SEAT" FOREIGN KEY ("SCREENING_SEAT_ID")
	  REFERENCES "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_SEAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REVIEW
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "FK_REVIEW_USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "C##MOVIE_SNIPER"."USERS" ("USER_ID") ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."REVIEW" ADD CONSTRAINT "FK_REVIEW_SCR_SEAT" FOREIGN KEY ("SCREENING_SEAT_ID")
	  REFERENCES "C##MOVIE_SNIPER"."SCREENINGSEAT" ("SCREENING_SEAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCREENING
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" ADD CONSTRAINT "FK_SCR_MOVIE" FOREIGN KEY ("MOVIE_ID")
	  REFERENCES "C##MOVIE_SNIPER"."MOVIE" ("MOVIE_ID") ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENING" ADD CONSTRAINT "FK_SCR_THEATER" FOREIGN KEY ("THEATER_ID")
	  REFERENCES "C##MOVIE_SNIPER"."THEATER" ("THEATER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SCREENINGSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" ADD CONSTRAINT "FK_SS_SCREENING" FOREIGN KEY ("SCREENING_ID")
	  REFERENCES "C##MOVIE_SNIPER"."SCREENING" ("SCREENING_ID") ENABLE;
  ALTER TABLE "C##MOVIE_SNIPER"."SCREENINGSEAT" ADD CONSTRAINT "FK_SS_SEAT" FOREIGN KEY ("SEAT_ID")
	  REFERENCES "C##MOVIE_SNIPER"."THEATERSEAT" ("SEAT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table THEATERSEAT
--------------------------------------------------------

  ALTER TABLE "C##MOVIE_SNIPER"."THEATERSEAT" ADD CONSTRAINT "FK_TS_THEATER" FOREIGN KEY ("THEATER_ID")
	  REFERENCES "C##MOVIE_SNIPER"."THEATER" ("THEATER_ID") ENABLE;
